pipeline {
    agent any
    environment {
        VENV = 'venv'
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'your-github-credentials-id', url: 'https://github.com/your-username/alx-backend-python.git'
            }
        }
        stage('Set up Python') {
            steps {
                sh 'python3 -m venv $VENV'
                sh './$VENV/bin/pip install --upgrade pip'
                sh './$VENV/bin/pip install -r messaging_app/messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh './$VENV/bin/pytest messaging_app/messaging_app/ --junitxml=pytest-report.xml'
            }
            post {
                always {
                    junit 'pytest-report.xml'
                }
            }
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
    }
}
