# Generated by Django 5.2.3 on 2025-06-14 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Whether the message has been edited'),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(help_text='Previous content before the edit')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the edit occurred')),
                ('edited_by', models.ForeignKey(help_text='User who made the edit', on_delete=django.db.models.deletion.CASCADE, related_name='message_edits', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='Message that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message History',
                'verbose_name_plural': 'Message Histories',
                'ordering': ['-edited_at'],
            },
        ),
    ]
